import type { NonprofitProfile, GrantRecommendation } from "../types";

/**
 * Read the mock/real toggle from localStorage.
 * Default to true (mock mode) if not set.
 */
function getUseMock(): boolean {
  return JSON.parse(localStorage.getItem("use_mock") ?? "true");
}

/**
 * Parse Gemini API response into GrantRecommendation[]
 * Assumes Gemini returns text like:
 * "Grant: ...\nFunder: ...\nDescription: ..."
 */
function parseGeminiResponse(data: any): GrantRecommendation[] {
  const recommendations: GrantRecommendation[] = [];

  if (data?.candidates) {
    data.candidates.forEach((candidate: any) => {
      const text: string = candidate?.content?.parts?.[0]?.text ?? "";
      const lines: string[] = text.split("\n").map((l: string) => l.trim());

      const grant: GrantRecommendation = {
        funderName:
          (lines.find((l: string) => l.startsWith("Funder:"))?.replace("Funder:", "").trim() as string) ||
          "Unknown Funder",
        grantName:
          (lines.find((l: string) => l.startsWith("Grant:"))?.replace("Grant:", "").trim() as string) ||
          "Untitled Grant",
        description:
          (lines.find((l: string) => l.startsWith("Description:"))?.replace("Description:", "").trim() as string) ||
          "",
        website: "https://example.org", // placeholder until Gemini provides URLs
        matchReason: "Generated by Gemini based on your profile",
      };

      recommendations.push(grant);
    });
  }

  return recommendations;
}

/**
 * findGrants
 * Given a nonprofit profile, returns a list of grant recommendations.
 */
export async function findGrants(
  profile: NonprofitProfile
): Promise<GrantRecommendation[]> {
  const apiKey = localStorage.getItem("gemini_api_key");
  if (!apiKey) {
    throw new Error("No Gemini API key found. Please enter your API key.");
  }

  const USE_MOCK = getUseMock();

  if (USE_MOCK) {
    const mockResults: GrantRecommendation[] = [
      {
        funderName: "Community Foundation of Mississippi",
        grantName: "Local Impact Grant",
        description:
          "Supports nonprofits addressing community needs such as food security, housing, and education.",
        website: "https://example.org/local-impact",
        matchReason: "Matches your mission to support underserved communities.",
      },
      {
        funderName: "National Arts Endowment",
        grantName: "Arts Innovation Grant",
        description:
          "Funds creative projects that expand access to arts and culture.",
        website: "https://example.org/arts-innovation",
        matchReason: "Aligns with your stated goals around cultural engagement.",
      },
      {
        funderName: "Green Futures Fund",
        grantName: "Sustainability Grant",
        description:
          "Provides resources for nonprofits working on environmental sustainability and climate resilience.",
        website: "https://example.org/sustainability",
        matchReason: "Connects with your nonprofit’s environmental initiatives.",
      },
    ];

    await new Promise((resolve) => setTimeout(resolve, 1000));
    return mockResults;
  }

  const response = await fetch(
    "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text: `Suggest grant opportunities for a nonprofit with the following profile:
                Organization: ${profile.orgName}
                Mission: ${profile.mission}
                Goals: ${profile.goals}
                Needs: ${profile.needs}
                Address: ${profile.address}
                Contact: ${profile.contactName}, ${profile.contactPhone}, ${profile.email}
                Website: ${profile.website}
                Tax ID: ${profile.taxId}`,
              },
            ],
          },
        ],
      }),
    }
  );

  if (!response.ok) {
    throw new Error(`Gemini API error: ${response.statusText}`);
  }

  const data = await response.json();
  return parseGeminiResponse(data);
}